name: Reusable workflow - Build image on Tag Pushka - dev

on:
  workflow_call:
    inputs:
      repository_name:
        required: true
        type: string
    secrets:
      CI_GITHUB_TOKEN:
        required: true
      ORG_PERSONAL_ACCESS_TOKEN:
        required: true

jobs:
  push_to_registry:
    name: Pushka to GitHub registry by Tags
    runs-on: ubuntu-latest
    steps:
      - name: Get the version
        run: echo "VERSION=$(echo $GITHUB_REF | cut -d / -f 3)" >> $GITHUB_ENV

      - name: Checkout
        uses: actions/checkout@v2

      - name: build&push
        uses: docker/build-push-action@v1
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.CI_GITHUB_TOKEN }}
          registry: ghcr.io
          repository: zebrainy/${{ inputs.repository_name }}
          tags: ${{ env.VERSION }}
      
      - name: Checkout k8s (dev branch)
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.ORG_PERSONAL_ACCESS_TOKEN }}
          repository: Zebrainy/k8s
          ref: dev-yc

      - name: Kustomize 
        run: |
          (cd ./deployments/${{ inputs.repository_name }}/ && kustomize edit set image IMAGENAME=ghcr.io/zebrainy/${{ inputs.repository_name }}:${{ env.VERSION }})
     
      - name: Push to DEV branch
        uses: github-actions-x/commit@v2.9
        with:
          github-token: ${{ secrets.ORG_PERSONAL_ACCESS_TOKEN }}
          push-branch: 'dev'
          commit-message: 'Update ${{ github.repository	}} to ${{ env.VERSION }}'
          force-add: 'true'
          name: Jnqa-ci