name: Reusable workflow - Build tag version

on:
  workflow_call:
    inputs:
      repository_name:
        required: true
        type: string
    secrets:
      GITHUB_TOKEN:
        required: true
      ORG_PERSONAL_ACCESS_TOKEN:
        required: true

jobs:
  push_to_registry:
    name: Build & upload to GitHub registry
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
           
      - name: package-version
        run: node -p -e '`PACKAGE_VERSION=${require("./package.json").version}`' >> $GITHUB_ENV

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '14.x'

      - name: Download script 
        run: curl https://zebrainy.github.io/scripts/map_github_ref_to_tag.js > map_github_ref_to_tag.js

      - name: Get tag name
        id: tag
        run: |
         echo "tag_name=$(node map_github_ref_to_tag.js ${{ github.ref }})" >> $GITHUB_OUTPUT

      - name: Tag new version
        uses: pkgdeps/action-package-version-to-git-tag@v2.0.2
        with:
          github_token: ${{ secrets.ORG_PERSONAL_ACCESS_TOKEN }}
          github_repo: ${{ github.repository }}
          version: ${{ env.PACKAGE_VERSION }}
          git_commit_sha: ${{ github.sha }}
          git_tag_prefix: ${{ steps.tag.outputs.tag_name }}