name: Reusable workflow - Build latest image - do

on:
  workflow_call:
    inputs:
      repository_name:
        required: true
        type: string
    secrets:
      CI_GITHUB_TOKEN:
        required: true
      ORG_PERSONAL_ACCESS_TOKEN:
        required: true

jobs:
  push_to_registry:
    name: Build & upload to GitHub registry
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
#     - name: Build and Push
#         uses: docker/build-push-action@v1
#         with:
#           username: ${{ github.actor }}
#           password: ${{ secrets.CI_GITHUB_TOKEN }}
#           registry: ghcr.io
#           repository: zebrainy/${{ inputs.repository_name }}
#           tags: latest
      
      - name: package-version
        run: node -p -e '`PACKAGE_VERSION=${require("./package.json").version}`' >> $GITHUB_ENV

      - name: Tag new version
        uses: pkgdeps/action-package-version-to-git-tag@v2.0.2
        with:
          github_token: ${{ secrets.ORG_PERSONAL_ACCESS_TOKEN }}
          github_repo: ${{ github.repository }}
          version: ${{ env.PACKAGE_VERSION }}
          git_commit_sha: ${{ github.sha }}
          git_tag_prefix: "do-v"
