name: Reusable workflow - Update actions

on:
  workflow_call:
    inputs:
      repository_name:
        required: true
        type: string
    secrets:
      CI_GITHUB_TOKEN:
        required: true
      ORG_PERSONAL_ACCESS_TOKEN:
        required: true

jobs:
  push_to_registry:
    name: Build & upload to GitHub registry
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Update Action 
        run: |
          # rm .github/workflows/*.yaml - к примеру лишнее убрать
          wget "<url нового action>" --output-document .github/workflows/onpush.yaml
          # wget "<url нового action>" --output-document .github/workflows/ontag.yaml - остальные
     
      - name: Push to Master branch
        uses: github-actions-x/commit@v2.9
        with:
          github-token: ${{ secrets.ORG_PERSONAL_ACCESS_TOKEN }}
          push-branch: 'master'
          commit-message: 'Update ${{ github.repository	}} to ${{ env.VERSION }}'
          force-add: 'true'
          name: Zebrainy-ci
