name: Reusable workflow - Build branch WebView-bundle version

on:
  workflow_call:
    inputs:
      bundle_name:
        required: true
        type: string
      build_command:
        required: false
        type: string
        default: ci:build

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '14.x'
          cache: 'yarn'

      - name: Install dependencies
        run: yarn

      - name: Build project
        run: export NODE_OPTIONS=--max_old_space_size=8192 && yarn ${{ inputs.build_command }}

        
      - name: Archive
        run: |
          pushd dist
          zip -r dist.zip *
          popd

      - name: Get branch name
        uses: nelonoel/branch-name@v1.0.1

      # Use branch name for whatever purpose
      - run: echo ${BRANCH_NAME}
        
      - name: Prepare S3 upload
        run: |
          mkdir -p s3/${BRANCH_NAME}
          mv dist/dist.zip s3/${BRANCH_NAME}/latest.zip
          mv dist s3/${BRANCH_NAME}/latest

      - name: Upload to S3 SELECTEL
        uses: Zebrainy/s3-sync-action@s1
        with:
          dirname: s3
          s3dirname: web-bundles/bundles/${{ inputs.bundle_name }}/branches
          bucketname: web-bundles
          AWS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID_SELECTEL }}
          AWS_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY_SELECTEL }} 

      - name: Print URLs
        run: |
          echo Selectel:
          echo "https://471631.selcdn.ru/web-bundles/web-bundles/bundles/${{ inputs.bundle_name }}/branches/${BRANCH_NAME}/latest/index.html"
          echo "https://471631.selcdn.ru/web-bundles/web-bundles/bundles/${{ inputs.bundle_name }}/branches/${BRANCH_NAME}/latest.zip
